### PR TITLE
pic tiffy

### PR DESCRIPTION
**Pull request by Katie-Schmitt**
added tiffy, because it is nicer, viw image link

### CODE REVIEW

**Comment by thnsch** [comment]
You like to leave the tent?

**Comment by Katie-Schmitt** [comment]
Yes, why not. Emergency tent.

**Comment by thnsch** [comment]
I see.

**Comment by Katie-Schmitt** [comment]
Are you going to merge?

**Comment by thnsch** [comment]
Yes.

**Pull request merged**
